<?php

const BOARD_TILES = [
  BOARD_TILE_DIAGONAL_CANYON => [
    CARD_REF_DIAGONAL_CANYON,
    BONUS_GAIN_3_PLACE_1_IGNORE_ROUGH,
    BONUS_ALL_GAIN_2,
    BONUS_ANOTHER_GAINS_4
  ],
  BOARD_TILE_L_SHAPED_RIVER => [
    CARD_REF_L_SHAPED_RIVER,
    BONUS_ALL_GAIN_2,
    BONUS_ANOTHER_GAINS_4,
    BONUS_YOU_5_ANOTHER_MINUS_2,
  ],
  BOARD_TILE_DIAGONAL_MEADOW => [
    CARD_REF_DIAGONAL_MEADOW,
    BONUS_ANOTHER_GAINS_4,
    BONUS_YOU_5_ANOTHER_MINUS_2,
    BONUS_GAIN_3_PLACE_1_IGNORE_ROUGH
  ],
  BOARD_TILE_CORNER_WATERFALL => [
    CARD_REF_CORNER_WATERFALL,
    BONUS_ANOTHER_GAINS_4,
    BONUS_GAIN_3_PLACE_1_IGNORE_ROUGH,
    BONUS_YOU_5_ANOTHER_MINUS_2,
  ],
  BOARD_TILE_V_ROCKS => [
    CARD_REF_V_ROCKS,
    BONUS_GAIN_3_PLACE_1_IGNORE_ROUGH,
    BONUS_YOU_5_ANOTHER_MINUS_2,
    BONUS_ALL_GAIN_2
  ],
  BOARD_TILE_SINGLE_SNOW => [
    CARD_REF_SINGLE_SNOW,
    BONUS_ANOTHER_GAINS_4,
    BONUS_GAIN_3_PLACE_1_IGNORE_ROUGH,
    BONUS_ALL_GAIN_2
  ],
];