<?php

const CARDS = [
  0 => [
    'deck' => CARD_DECK_SUPPORT,
    'pattern' => [],
    'spaces' => [
      SPACE_TREE_TEAL,
      SPACE_NONE,
      SPACE_NORMAL,
      SPACE_NONE,
      SPACE_TREE_TEAL,
      SPACE_NONE,
      SPACE_ROUGH,
      SPACE_OASIS,
      SPACE_ROUGH,
    ],
  ],
  1 => [
    'deck' => CARD_DECK_SUPPORT,
    'pattern' => [],
    'spaces' => [
      SPACE_OASIS,
      SPACE_NONE,
      SPACE_NORMAL,
      SPACE_NONE,
      SPACE_ROUGH,
      SPACE_TREE_RED,
      SPACE_TREE_RED,
      SPACE_ROUGH,
      SPACE_NONE,
    ]
  ],
  2 => [
    'deck' => CARD_DECK_SUPPORT,
    'pattern' => [],
    'spaces' => [
      SPACE_TREE_BROWN,
      SPACE_NONE,
      SPACE_TREE_BROWN,
      SPACE_OASIS,
      SPACE_NONE,
      SPACE_NONE,
      SPACE_ROUGH,
      SPACE_ROUGH,
      SPACE_NORMAL,
    ]
  ],
  3 => [
    'deck' => CARD_DECK_SUPPORT,
    'pattern' => [],
    'spaces' => [
      SPACE_NONE,
      SPACE_NONE,
      SPACE_NORMAL,
      SPACE_NONE,
      SPACE_OASIS,
      SPACE_NORMAL,
      SPACE_TREE_BROWN,
      SPACE_TREE_BROWN,
    ]
  ],
  4 => [
    'deck' => CARD_DECK_SUPPORT,
    'pattern' => [],
    'spaces' => [
      SPACE_TREE_TEAL,
      SPACE_NONE,
      SPACE_NORMAL,
      SPACE_OASIS,
      SPACE_NONE,
      SPACE_NORMAL,
      SPACE_NONE,
      SPACE_NORMAL,
      SPACE_TREE_TEAL
    ]
  ],
  5 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [
      SPACE_NONE,
      SPACE_NONE,
      SPACE_NORMAL,
      SPACE_TREE_GREEN,
      SPACE_TREE_GREEN,
      SPACE_NONE,
      SPACE_OASIS,
      SPACE_NONE,
      SPACE_NORMAL,
    ]
  ],
  6 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => []
  ],
  7 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  8 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  9 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  10 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  11 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  12 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  13 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  14 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  15 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  16 => [
    'deck' => CARD_DECK_STARTING,
    'pattern' => [],
    'spaces' => [],
  ],
  17 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  18 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  19 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  20 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  21 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  22 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  23 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  24 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  25 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  26 => [
    'deck' => CARD_DECK_FIRST,
    'pattern' => [],
    'spaces' => [],
  ],
  27 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  28 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  29 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  30 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  31 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  32 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  33 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  34 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  35 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  36 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  37 => [
    'deck' => CARD_DECK_SECOND,
    'pattern' => [],
    'spaces' => [],
  ],
  38 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  39 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  40 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  41 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  42 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  43 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  44 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  45 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  46 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  47 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  48 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  49 => [
    'deck' => CARD_DECK_THIRD,
    'pattern' => [],
    'spaces' => [],
  ],
  50 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_FIRST],
  51 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_FIRST],
  52 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_FIRST],
  53 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_FIRST],
  54 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_FIRST],
  55 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_FIRST],
  56 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_FIRST],
  57 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_SECOND],
  58 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_SECOND],
  59 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_SECOND],
  60 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_SECOND],
  61 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_SECOND],
  62 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_SECOND],
  63 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_THIRD],
  64 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_THIRD],
  65 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_THIRD],
  66 => ['type' => CARD_TYPE_LION, 'deck' => CARD_DECK_THIRD],
  67 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_THIRD],
  68 => ['type' => CARD_TYPE_MATRIARCH, 'deck' => CARD_DECK_THIRD],
];

const BOARD_SPACES = [
  BOARD_TILE_DIAGONAL_CANYON => [
    SPACE_LANDMARK,
    SPACE_NONE,
    SPACE_ROUGH,
    SPACE_LANDMARK,
    SPACE_NONE,
    SPACE_NONE,
    SPACE_ROUGH,
    SPACE_LANDMARK,
    SPACE_NORMAL
  ],
  BOARD_TILE_L_SHAPED_RIVER => [
    SPACE_LANDMARK,
    SPACE_NONE,
    SPACE_LANDMARK,
    SPACE_ROUGH,
    SPACE_ROUGH,
    SPACE_NONE,
    SPACE_LANDMARK,
    SPACE_LANDMARK,
    SPACE_NONE,
  ],
  BOARD_TILE_DIAGONAL_MEADOW => [
    SPACE_LANDMARK,
    SPACE_NONE,
    SPACE_NONE,
    SPACE_NORMAL,
    SPACE_NONE,
    SPACE_NORMAL,
    SPACE_NONE,
    SPACE_LANDMARK,
    SPACE_NORMAL,
  ],
  BOARD_TILE_CORNER_WATERFALL => [
    SPACE_ROUGH,
    SPACE_LANDMARK,
    SPACE_LANDMARK,
    SPACE_NORMAL,
    SPACE_NORMAL,
    SPACE_NORMAL,
    SPACE_NONE,
    SPACE_NONE,
    SPACE_LANDMARK,
  ],
  BOARD_TILE_V_ROCKS => [
    SPACE_NORMAL,
    SPACE_ROUGH,
    SPACE_LANDMARK,
    SPACE_NONE,
    SPACE_NONE,
    SPACE_NORMAL,
    SPACE_LANDMARK,
    SPACE_ROUGH,
    SPACE_LANDMARK,
  ],
  BOARD_TILE_SINGLE_SNOW => [
    SPACE_LANDMARK,
    SPACE_NORMAL,
    SPACE_NONE,
    SPACE_NONE,
    SPACE_NONE,
    SPACE_NORMAL,
    SPACE_NONE,
    SPACE_NONE,
    SPACE_NONE,
  ]
];