<?php

namespace Bga\Games\Tembo;

/**
 * User preferences
 */
const OPTION_CONFIRM = 103;
const OPTION_CONFIRM_DISABLED = 0;
const OPTION_CONFIRM_TIMER = 1;
const OPTION_CONFIRM_ENABLED = 2;

const OPTION_CONFIRM_UNDOABLE = 104;

const OPTION_ENABLED = 1;
const OPTION_DISABLED = 0;
const OPTION_FIRST_GAME = 110;
const OPTION_JOURNEY = 111;
const OPTION_DIFFICULTY = 112;
const OPTION_EVENTS = 113;